export const { sin, cos, hypot, min, max, PI } = Math;
export const X = 0, Y = 1;
export const TWO_PI = PI * 2;
export const colorToHex = (r, g, b, a = 255) => `#${[r,g,b,a].map(n=>Number(n).toString(16).padStart(2, '0')).join('')}`;
export const clamp = (n, minA = 0, maxB = 1) => min(max(n, minA), maxB);
export const angle2Vector = (a) => [cos(a), sin(a)];
export const magnitude = ([x, y]) => hypot(x, y);
export const vector2Polar = ([x, y]) => ({ angle: Math.atan2(y, x), magnitude: hypot(x, y) });
export const distance = ([x1, y1], [x2, y2]) => hypot(x2 - x1, y2 - y1);
export const setPos = (destPos, [x, y]) => { destPos[X] = x; destPos[Y] = y; };
export const addVectors = ([x1, y1], [x2, y2]) => [x1 + x2, y1 + y2];
export const subtractVectors = ([x1, y1], [x2, y2]) => [x1 - x2, y1 - y2];
